apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  REDIS_HOST: "redis.app.svc.cluster.local"
  REDIS_PORT: "6379"

  DB_HOST: "video-reliability-dev-postgres.cgvqi448ixth.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "videodb"
  DB_USER: "videouser"
