apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  namespace: app
  labels:
    app: upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      containers:
        - name: upload-service
          image: 907759099913.dkr.ecr.us-east-1.amazonaws.com/video-upload:1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: app
  labels:
    app: upload-service
spec:
  selector:
    app: upload-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
